"use strict";
var basket = 10;
basket = true;
basket = "banana";
console.log(basket);
var vList = [1, false, "happy"];
console.log(vList[0]);
var num1 = 50;
var num2 = 50;
// num1.noMethods();
num2.noMethods();
var number2 = 50;
console.log(typeof number2);
// console.log(number2.toFixed(1));
